############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About Us"
weight = 2

[[main]]
parent = "About Us"
name = "Our Team"
pageRef = "/team"
weight = 3

[[main]]
name = "Projects"
pageRef = "/projects"
weight = 4

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 4

