############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Our Team"
pageRef = "/team"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 4

